### ISSUE TITLE
Should provide mechanism to halt backoff on hard errors.

### ISSUE THREAD

**Issue by alaska** [cenk/backoff#26]
Similar to #19 and #22, I believe you should provide a mechanism to stop the backoff early.  Certain errors are not retryable and, should these be encountered, the backoff should be stopped immediately, and the error returned to the caller for handling.  Since you do not provide a mechanism to stop the backoff directly, the solution to #19 (wrap the operation function) is inadequate for this case.  If you provide:
```
func ConditionalRetry(o Operation, c Conditional, b Backoff) error
func ConditionalRetryNotify(o Operation, c Conditional, n Notify, b Backoff) error
```
 As suggested, you will be able to satisfy this use case AND address #22 without breaking backwards compatibility.

A ticker is inadequate since, as you specify in your documentation:

> Ticks will continue to arrive when the previous operation is still running, so operations that take a while to fail could run in quick succession.

Clearly, there is a need for a blocking retry mechanism that can also abort in the case of an un-retryable error.

**Comment by cenk** [comment]
Hello @alaska. I don't want to add more functions to this library. I want to keep it simple and small. If you have more complex needs I suggest writing your own logic inside your application. You can start by copying `Retry`, it is a very small function.

**Comment by pjebs** [comment]
@alaska I fixed it in this fork: https://github.com/pjebs/backoff
