### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by pjebs** [cenk/backoff#29]
```
operation := func() error {
    err := importantOperation()
    if err == nil {
      return nil
   } else if x == A {
   //Continue retrying as normal
  } else { 
  //Quit retrying
  }

}
```

**Comment by pjebs** [comment]
@cenk  Is there some way I can under some conditions stop the retrying process?
I've read the documentation numerous times but I don't seem to be able to find a way.

The only way I can think of making this work is to define the `NewExponentialBackOff()` as a **reference** before the definition of `operation` func. And then inside the `operation` func, call a method to `stop()` the `Backoff` interface.

Perhaps you can update the `Backoff` interface to include a `Stop()` method which will guarantee to stop retrying.

**Comment by pjebs** [comment]
The only messy workaround I can think of is to make `NewExponentialBackOff.MaxElapsedTime`= 1 nanosecond. I haven't tested it but I believe that would work.

**Comment by pjebs** [comment]
@cenk ?

**Comment by cenk** [comment]
Hello @pjebs. Sorry about the late reply.

Currently there is no way of stopping the retry process when use `Retry` function.

> Perhaps you can update the Backoff interface to include a Stop() method which will guarantee to stop retrying.

I cannot simply change the public interface because this package is used in many projects. That would break them.

My recommendation is that you copy `Retry` into your project and modify as you like, it is a really small function. Maybe this is not the best solution but worked well up to this time.

**Comment by pjebs** [comment]
would `NewExponentialBackOff.MaxElapsedTime`= 1 work?

**Comment by pjebs** [comment]
what about if you were to make a new branch for version 2 and then use gopkg (http://labix.org/gopkg.in) for `go get`

**Comment by cenk** [comment]
> would NewExponentialBackOff.MaxElapsedTime= 1 work?

It may or may not work work depending on the hardware and operation system. It is a hack and you should not rely on that. Also it is harder to understand when you read because the reader must know the implementation in order to understand that it is going to stop `BackOff`.

**Comment by codeactual** [comment]
@pjebs I needed the same capability and just used the `Ticker` instead so I could customize the logic inside a `for`.

**Comment by cenk** [comment]
> what about if you were to make a new branch for version 2

I want to keep this package as simple and small as possible. For this reason it will not happen.

**Comment by cenk** [comment]
@pjebs @codeactual there is a slight difference between `Retry` and `Ticker`.

`Retry` sleeps when the operation fails.

When use use `Ticker` with a for/select idiom, ticks are sent while the operation continues. In other words, next tick may come before your operation still in progress. You should keep this in mind.

**Comment by pjebs** [comment]
I fixed it in this fork: https://github.com/pjebs/backoff
