### ISSUE TITLE
ExponentialBackoff does not honor set InitialInterval

### ISSUE THREAD

**Issue by Southern** [cenk/backoff#30]
I have been trying to use `ExponentialBackoff` with an `InitialInterval` of `5*time.Second`, but it continues to use the default of `500*time.Millisecond`.

```
expBackoff := backoff.NewExponentialBackoff()
expBackoff.InitialInterval = 5*time.Second
```

With the first `expBackoff.NextBackOff()` that's logged:
```
DEBU[0000] Retrying login in 582.280027ms
```

**Comment by cenk** [comment]
You can't change `InitialInterval` after `ExponentialBackOff` is created.

However, you can do:
```
b := &backoff.ExponentialBackOff{
	InitialInterval:     5 * time.Second,
	RandomizationFactor: backoff.DefaultRandomizationFactor,
	Multiplier:          backoff.DefaultMultiplier,
	MaxInterval:         backoff.DefaultMaxInterval,
	MaxElapsedTime:      backoff.DefaultMaxElapsedTime,
	Clock:               backoff.SystemClock,
}
b.Reset()
```

**Comment by pjebs** [comment]
Can you change `MaxElapsedTime` after `NewExponentialBackoff()`?

**Comment by cenk** [comment]
The behavior is undocumented so you should not rely on it. 

It is used in `NextBackOff` function. If you change `MaxElapsedTime` before `NextBackOff` is called then it should be okay.
